In [1]:
import os
import ipynbname
import numpy as np
import glob
from astropy.io import fits
import warnings
warnings.filterwarnings('ignore')

nb_fname = ipynbname.name()
nb_path = str(ipynbname.path())

In [2]:
nb_path

'/Users/RuoyanWang/Documents/LEICESTER/h3p/02jun17/code/h3p_glob.ipynb'

In [3]:
spec_dir = os.path.join(os.path.abspath(nb_path + '/../../'), 'spec/')
spec_dir

'/Users/RuoyanWang/Documents/LEICESTER/h3p/02jun17/spec/'

In [8]:
sorted(glob.glob(spec_dir+'order36/jun02s*'))

['/Users/RuoyanWang/Documents/LEICESTER/h3p/02jun17/spec/order36/jun02s0022_order36.fits',
 '/Users/RuoyanWang/Documents/LEICESTER/h3p/02jun17/spec/order36/jun02s0023_order36.fits',
 '/Users/RuoyanWang/Documents/LEICESTER/h3p/02jun17/spec/order36/jun02s0024_order36.fits',
 '/Users/RuoyanWang/Documents/LEICESTER/h3p/02jun17/spec/order36/jun02s0025_order36.fits',
 '/Users/RuoyanWang/Documents/LEICESTER/h3p/02jun17/spec/order36/jun02s0026_order36.fits',
 '/Users/RuoyanWang/Documents/LEICESTER/h3p/02jun17/spec/order36/jun02s0027_order36.fits',
 '/Users/RuoyanWang/Documents/LEICESTER/h3p/02jun17/spec/order36/jun02s0028_order36.fits',
 '/Users/RuoyanWang/Documents/LEICESTER/h3p/02jun17/spec/order36/jun02s0029_order36.fits',
 '/Users/RuoyanWang/Documents/LEICESTER/h3p/02jun17/spec/order36/jun02s0030_order36.fits',
 '/Users/RuoyanWang/Documents/LEICESTER/h3p/02jun17/spec/order36/jun02s0031_order36.fits',
 '/Users/RuoyanWang/Documents/LEICESTER/h3p/02jun17/spec/order36/jun02s0032_order36.fits',

In [13]:
def read_file(path):
    
    data_list = []
    
    data = sorted(glob.glob(path))
    
    for i in range(len(data)):
        hdu = fits.getdata(data[i])
        data_list.append(hdu)
        
    data_array = np.array(data_list)
    
    return data_array

# filepath = spec_dir+'order36/new_frame/'

order36_data = read_file(spec_dir+'order36/new_frame/*.fits')
order32_data = read_file(spec_dir+'order32/new_frame/*.fits')
order37_data = read_file(spec_dir+'order37/new_frame/*.fits')
order35_data = read_file(spec_dir+'order35/new_frame/*.fits')
order34_data = read_file(spec_dir+'order34/new_frame/*.fits')

In [158]:
order36_data

array([[[ 1.9221477e+02,  1.4110282e+01, -1.4110001e+02, ...,
          8.5538254e+01,  8.5879929e+01,  2.9760536e+01],
        [ 1.8001239e+02,  1.5024603e+01, -1.5431122e+02, ...,
          8.9706642e+01,  9.6457222e+01,  2.1295717e+01],
        [ 1.6925246e+02,  1.8331032e+01, -1.6412703e+02, ...,
          9.3129837e+01,  1.0565691e+02,  1.3998590e+01],
        ...,
        [ 4.1893402e+01,  4.6106403e+01, -6.6620636e+01, ...,
         -1.0716830e+02,  5.3521276e+00,  1.4658173e+02],
        [ 4.8967632e+01,  3.3375050e+01, -2.3939838e+01, ...,
         -1.1103947e+02,  1.2777783e+01,  1.4931264e+02],
        [ 5.2504749e+01,  2.7009371e+01, -2.5994384e+00, ...,
         -1.1297505e+02,  1.6490612e+01,  1.5067809e+02]],

       [[ 1.7276237e+02,  5.1135506e+01, -9.8375565e+01, ...,
          9.2856529e+01,  1.0043721e+02,  5.6384171e+01],
        [ 1.7325601e+02,  4.1556362e+01, -1.2992981e+02, ...,
          8.7948120e+01,  9.4106003e+01,  5.6865177e+01],
        [ 1.7560381e+02, 

In [155]:
def calc_avg(order, start, stop, init):
    """
    Calculate the average of data frames.
    
    order: echelle order of spectrograph
    start: index of first fits file to process
    stop: index of last fits file to process
    init: index of first fits file of all
    
    return: the average of ranged fits files in the same shape as individual.
    
    An example: a folder contains fits files from order 36 ranging from 22 to 111 and 
        the files to be processed are 32 to 41. In this case, order = order36, start = 32, 
        stop = 41, init = 22. The order is a self defined variable name, 
        typically an array of 2d spectra data, eg. order.shape = (90, 264, 1024).
        The returned result would be a single 2d data frame in a shape of (264, 1024),
        with each pixel an average of the input fits files at the same pixel position.
    """
    avg = np.mean((order[start-init:stop-init+1]), axis=0)
    
    return avg

int0 = 22
flat0 = 32
flat1 = 41
dark0 = 22
dark1 = 31


avg_flat_order32 = calc_avg(order32_data, flat0, flat1, int0)
avg_flat_order34 = calc_avg(order34_data, flat0, flat1, int0)
avg_flat_order35 = calc_avg(order35_data, flat0, flat1, int0)
avg_flat_order36 = calc_avg(order36_data, flat0, flat1, int0)
avg_flat_order37 = calc_avg(order37_data, flat0, flat1, int0)

avg_dark_order32 = calc_avg(order32_data, dark0, dark1, int0)
avg_dark_order34 = calc_avg(order34_data, dark0, dark1, int0)
avg_dark_order35 = calc_avg(order35_data, dark0, dark1, int0)
avg_dark_order36 = calc_avg(order36_data, dark0, dark1, int0)
avg_dark_order37 = calc_avg(order37_data, dark0, dark1, int0)

In [143]:
def fits_header_utc_to_second(path, fn):

    data = sorted(glob.glob(path))
    
    hdu_header = fits.open(data[fn-1], ignore_missing_end=True)[0].header
    
    h = float(hdu_header['UTC'].split(':')[0])
    m = float(hdu_header['UTC'].split(':')[1])
    s = float(hdu_header['UTC'].split(':')[2])
    
    seconds = h * 3600 + m * 60 + s
    
    return seconds

fits_header_utc_to_second(spec_dir+'jun02s*', 61)

23126.29

In [22]:
# scale the sky frame linearly to account for change of sky brightness during observation
# refer to equation on page 9 of Stallard_et_al_2019, DOI:https://doi.org/10.1098/rsta.2018.0405

sky_frame = sorted([59,51,72,60,78,91,103])
sky_frame

[51, 59, 60, 72, 78, 91, 103]

In [40]:
order36_data.shape

(90, 264, 1024)

In [48]:
def scale_sky_frame(data, datfn, sky_fn1, sky_fn2, init):
    
    if datfn > sky_fn1 and datfn < sky_fn2:
        
        sky1 = data[sky_fn1-init]
        sky2 = data[sky_fn2-init]
        
        t1 = fits_header_utc_to_second(sky_fn1) 
        t2 = fits_header_utc_to_second(sky_fn2)
        td = fits_header_utc_to_second(datfn)
        
        sky_scaled = sky1 * ((t2 - td) / (t2 - t1)) + sky2 * ((td - t1) / (t2 - t1))
        
        return sky_scaled
        
    elif datfn == sky_fn1 or datfn == sky_fn2:
        return 'Input frame is a sky frame'
    else:
        return 'Input frame number exceeded range'
    
#     print (sky1, sky2)
    


#     
    

fn = 60
scale_sky_frame(order36_data, fn, 51, 59, 22)

'Input frame number exceeded range'

In [79]:
def scale_sky_frame(data, datfn, skyfn, init):
    
    for i in range(len(skyfn)-1):
        sky1, sky2 = (skyfn[i], skyfn[i+1])
        
        
    sky1 = data[fn-init]
    print(sky1)
    sky2 = data[fn[i+1]-init]
    
    
#         if fn > sky_fn1 and fn < sky_fn2:

        t1 = fits_header_utc_to_second(skyfn[i]) 
        t2 = fits_header_utc_to_second(skyfn[i+1])
        td = fits_header_utc_to_second(fn)

        sky_scaled = sky1 * ((t2 - td) / (t2 - t1)) + sky2 * ((td - t1) / (t2 - t1))


        return sky_scaled

#         elif fn == sky_fn1 or fn == sky_fn2:
#             return 'Input frame is a sky frame'
#         else:
#             return 'Input frame number exceeded range'
    
sky_frame = [51,59,60,72,78,91,103]

scale_sky_frame(order36_data, 61, sky_frame, 22)

UnboundLocalError: local variable 'i' referenced before assignment

In [157]:
def scale_sky_frame(data, datfn, skyfn, init):
    
    for i in range(len(skyfn)-1):
        if datfn > skyfn[i] and datfn < skyfn[i+1]:
            skyfn1, skyfn2 = skyfn[i], skyfn[i+1]
            
            sky1, sky2 = data[skyfn1-init], data[skyfn2-init]
            
            t1 = fits_header_utc_to_second(path, skyfn1)
            t2 = fits_header_utc_to_second(path, skyfn2)
            td = fits_header_utc_to_second(path, datfn)
            
            sky_scaled = sky1 * ((t2 - td) / (t2 - t1)) + sky2 * ((td - t1) / (t2 - t1))
            
            return sky_scaled
        
spec36_reducelist = []
        
for fn in range(60,104):
    if fn in sky_frame:
        continue
    else:
        skyframe36 = scale_sky_frame(data=order36_data, datfn=fn, skyfn=sky_frame, init=int0)
        
        reduce_spec36 = (order36_data[fn-int0] - skyframe36) / (avg_flat_order36 - avg_dark_order36)
        reduce_spec36[reduce_spec36<0] = 0
    
        spec36_reducelist.append(reduce_spec36)
spec36_reduced = np.array(spec36_reducelist)
spec36_reduced[17][17][34]

0.0009194715

In [148]:
sky_frame = [51,59,60,72,78,79,91,103]
path = spec_dir+'jun02s*'
init=22

for fn in range(60,62):
    if fn in sky_frame:
        continue
    else:
        for i in range(len(sky_frame)-1):
            if fn > sky_frame[i] and fn < sky_frame[i+1]:
                
                skyfn1, skyfn2 = sky_frame[i], sky_frame[i+1]
                
                sky1, sky2 = order36_data[skyfn1-init], order36_data[skyfn2-init]
                
                t1 = fits_header_utc_to_second(path, skyfn1)
                t2 = fits_header_utc_to_second(path, skyfn2)
                td = fits_header_utc_to_second(path, fn)
                
                sky_scaled = sky1 * ((t2 - td) / (t2 - t1)) + sky2 * ((td - t1) / (t2 - t1))
                
                print(sky_scaled)

[[45.01796  46.60552  40.471027 ... 20.816587 20.816587 20.816587]
 [36.682396 33.5708   32.12086  ... 16.737843 16.737843 16.737843]
 [28.341234 20.95667  23.162163 ... 13.741157 13.741157 13.741157]
 ...
 [66.02234  64.038124 63.498665 ... 20.073051 23.43323  22.842632]
 [56.112488 48.83745  46.859528 ... 14.118076 17.976141 31.629742]
 [51.157566 41.237106 38.539963 ... 11.14059  15.247596 36.023296]]


In [124]:
fits_header_utc_to_second(spec_dir+'jun02s*', 72)

24227.75

In [117]:
order36_data[72-22]

array([[49.397823 , 39.480164 , 34.110256 , ..., 20.223318 , 20.223318 ,
        20.223318 ],
       [43.447914 , 36.36967  , 33.337543 , ..., 15.39325  , 15.39325  ,
        15.39325  ],
       [36.61899  , 32.10458  , 31.087847 , ..., 11.542376 , 11.542376 ,
        11.542376 ],
       ...,
       [67.156136 , 69.168465 , 62.689644 , ..., 21.496256 , 22.231009 ,
        18.156199 ],
       [58.100216 , 65.478355 , 41.724003 , ..., 14.270406 , 12.738768 ,
        24.41958  ],
       [53.572258 , 63.6333   , 31.241179 , ..., 10.65748  ,  7.9926467,
        27.551271 ]], dtype=float32)

In [107]:
sky2

103

In [78]:
def scale_sky_frame(data, fn_spec):
    """
    confirmed sky frames: 51, 59, 60, 72, 78, 79, 91, 103
    """
    sky_frame = [51,59,60,72,78,91,103]
    if fn_spec >=0 and fn_spec < 51:
        fn_sky1 = 51
        fn_sky2 = 59
    elif fn_spec > 51 and fn_spec < 60:
        fn_sky1 = 51 # frame number of sky1
        fn_sky2 = 59 # frame number of sky2
    elif fn_spec > 60 and fn_spec < 72:
        fn_sky1 = 60
        fn_sky2 = 72
    elif fn_spec > 72 and fn_spec < 78:
        fn_sky1 = 72
        fn_sky2 = 78
    elif fn_spec > 78 and fn_spec < 91:
        fn_sky1 = 79
        fn_sky2 = 91
    elif fn_spec > 91 and fn_spec < 103:
        fn_sky1 = 91
        fn_sky2 = 103
    elif fn_spec > 103:
        fn_sky1 = 91
        fn_sky2 = 103

    sky1 = data[fn_sky1-22]
    print(sky1)
    sky2 = data[fn_sky2-22]

    t1 = fits_header_utc_to_second(fn_sky1) 
    t2 = fits_header_utc_to_second(fn_sky2)
    td = fits_header_utc_to_second(fn_spec)

    sky_final = sky1 * ((t2 - td) / (t2 - t1)) + sky2 * ((td - t1) / (t2 - t1))
    return sky_final

scale_sky_frame(order36_data, 61)

[[44.61455  47.261803 41.05689  ... 20.871231 20.871231 20.871231]
 [36.05926  33.31301  32.0088   ... 16.861687 16.861687 16.861687]
 [27.578814 19.929892 22.432169 ... 13.943676 13.943676 13.943676]
 ...
 [65.917915 63.565598 63.57318  ... 19.941967 23.543959 23.274277]
 [55.929413 47.304737 47.33254  ... 14.104046 18.458529 32.293835]
 [50.93516  39.17431  39.21222  ... 11.185086 15.915813 36.80361 ]]


array([[45.01796 , 46.60552 , 40.471027, ..., 20.816587, 20.816587,
        20.816587],
       [36.682396, 33.5708  , 32.12086 , ..., 16.737843, 16.737843,
        16.737843],
       [28.341234, 20.95667 , 23.162163, ..., 13.741157, 13.741157,
        13.741157],
       ...,
       [66.02234 , 64.038124, 63.498665, ..., 20.073051, 23.43323 ,
        22.842632],
       [56.112488, 48.83745 , 46.859528, ..., 14.118076, 17.976141,
        31.629742],
       [51.157566, 41.237106, 38.539963, ..., 11.14059 , 15.247596,
        36.023296]], dtype=float32)

In [141]:
notebook_path = os.path.abspath('h3p_map_stack.ipynb' + "/../")
filepath = os.path.join(os.path.dirname(notebook_path), 'spec/')

# convert observation time (UTC) to seconds 
def fits_header_utc_to_second(fn):
    # fn = frame_number
    if fn >= 0 and fn < 10:
        hdu_header = fits.open(filepath + 'jun02s000' + '{}.fits'.format(fn), ignore_missing_end=True)[0].header
    elif fn >= 10 and fn < 100:
        hdu_header = fits.open(filepath + 'jun02s00' + '{}.fits'.format(fn), ignore_missing_end=True)[0].header
    elif fn >= 100 and fn < 111:
        hdu_header = fits.open(filepath + 'jun02s0' + '{}.fits'.format(fn), ignore_missing_end=True)[0].header
    elif fn >= 111:
        pass
    
    h = float(hdu_header['UTC'].split(':')[0])
    m = float(hdu_header['UTC'].split(':')[1])
    s = float(hdu_header['UTC'].split(':')[2])
    
    seconds = h * 3600 + m * 60 + s
    return seconds

def scale_sky_frame(data, fn_spec):
    """
    confirmed sky frames: 51, 59, 60, 72, 78, 79, 91, 103
    """
    sky_frame = [51,59,60,72,78,91,103]
    if fn_spec >=0 and fn_spec < 51:
        fn_sky1 = 51
        fn_sky2 = 59
    elif fn_spec > 51 and fn_spec < 60:
        fn_sky1 = 51 # frame number of sky1
        fn_sky2 = 59 # frame number of sky2
    elif fn_spec > 60 and fn_spec < 72:
        fn_sky1 = 60
        fn_sky2 = 72
    elif fn_spec > 72 and fn_spec < 78:
        fn_sky1 = 72
        fn_sky2 = 78
    elif fn_spec > 78 and fn_spec < 91:
        fn_sky1 = 79
        fn_sky2 = 91
    elif fn_spec > 91 and fn_spec < 103:
        fn_sky1 = 91
        fn_sky2 = 103
    elif fn_spec > 103:
        fn_sky1 = 91
        fn_sky2 = 103

    sky1 = data[fn_sky1-22]
    sky2 = data[fn_sky2-22]

    t1 = fits_header_utc_to_second(fn_sky1) 
    t2 = fits_header_utc_to_second(fn_sky2)
    td = fits_header_utc_to_second(fn_spec)

    sky_final = sky1 * ((t2 - td) / (t2 - t1)) + sky2 * ((td - t1) / (t2 - t1))
    return sky_final

spec36_reducelist = []

for i in range(60, 104):
    sky_frame = (51, 59, 60, 72, 78, 79, 91, 103)
    
    if i in sky_frame:
        continue
    elif i not in sky_frame:
        skyframe36 = scale_sky_frame(order36_data, i)
        print(skyframe36)
    
#         reduce_spec36 = (order36_data[i-22] - skyframe36) / (avg_flat_order36 - avg_dark_order36)
#         reduce_spec36[reduce_spec36<0] = 0
    
#         spec36_reducelist.append(reduce_spec36)
# spec36_reduced = np.array(spec36_reducelist)
# spec36_reduced
# spec36_stacked = np.sum((spec36_reduced), axis=0)

[[45.01796  46.60552  40.471027 ... 20.816587 20.816587 20.816587]
 [36.682396 33.5708   32.12086  ... 16.737843 16.737843 16.737843]
 [28.341234 20.95667  23.162163 ... 13.741157 13.741157 13.741157]
 ...
 [66.02234  64.038124 63.498665 ... 20.073051 23.43323  22.842632]
 [56.112488 48.83745  46.859528 ... 14.118076 17.976141 31.629742]
 [51.157566 41.237106 38.539963 ... 11.14059  15.247596 36.023296]]
[[45.40745  45.97188  39.90538  ... 20.76383  20.76383  20.76383 ]
 [37.28404  33.8197   32.229057 ... 16.61827  16.61827  16.61827 ]
 [29.077354 21.948025 23.866974 ... 13.545626 13.545626 13.545626]
 ...
 [66.12317  64.494354 63.42672  ... 20.199614 23.326317 22.42588 ]
 [56.289253 50.317284 46.402843 ... 14.131622 17.510393 30.98856 ]
 [51.3723   43.228745 37.890903 ... 11.097628 14.602432 35.2699  ]]
[[45.804497  45.32595   39.328762  ... 20.710049  20.710049  20.710049 ]
 [37.89735   34.07342   32.339355  ... 16.496382  16.496382  16.496382 ]
 [29.827755  22.95861   24.585457  ...

 [50.514984  51.074234  31.330248  ... -1.6630177  5.4373345 21.929317 ]]
[[44.441654  44.75624   44.46645   ... 15.766813  15.766813  15.766813 ]
 [37.382843  35.44129   38.736954  ... 15.032152  15.032152  15.032152 ]
 [29.775871  25.96176   32.178516  ... 14.357045  14.357045  14.357045 ]
 ...
 [55.545044  55.71014   51.965046  ... 11.82635   17.94688   21.590607 ]
 [51.893204  52.498528  38.76728   ...  2.961461   9.8333    22.272022 ]
 [50.067284  50.89272   32.168396  ... -1.4709836  5.7765102 22.612728 ]]
[[44.67254   44.59704   44.42752   ... 15.178497  15.178497  15.178497 ]
 [37.57548   35.26673   38.41611   ... 14.196264  14.196264  14.196264 ]
 [29.950735  25.82383   31.676147  ... 13.352964  13.352964  13.352964 ]
 ...
 [54.432266  54.65189   51.11567   ... 11.806149  17.795225  21.306387 ]
 [51.2166    52.02184   39.05642   ...  3.085843  10.014328  22.643894 ]
 [49.608765  50.706814  33.02679   ... -1.2743104  6.1238785 23.312647 ]]
[[44.890736  44.446587  44.39073   ...

In [164]:
sky2_fn

59

In [158]:
order36_data[61-22]

array([[ 70.31375 ,  67.8905  ,  60.92134 , ...,  35.691166,  35.691166,
         35.691166],
       [ 64.68312 ,  61.73552 ,  55.56904 , ...,  30.916517,  30.916517,
         30.916517],
       [ 58.377613,  54.943478,  49.868843, ...,  26.832708,  26.832708,
         26.832708],
       ...,
       [103.08405 ,  97.9694  , 102.622665, ...,  27.00721 ,  34.27204 ,
         32.0056  ],
       [ 87.58047 ,  68.82776 ,  85.8888  , ...,  17.722452,  20.083712,
         33.0396  ],
       [ 79.828674,  54.256935,  77.52187 , ...,  13.080073,  12.989546,
         33.5566  ]], dtype=float32)

In [155]:
skyframe36.shape

(264, 1024)

In [51]:


order36_data_list = []

order36 = sorted(glob.glob(filepath+'order36/new_frame/*.fits'))

for i in range(len(order36)):
    hdu_order36 = fits.getdata(order36[i])
    order36_data_list.append(hdu_order36)
    
order36_data = np.array(order36_data_list)
order36_data

array([[[ 1.9221477e+02,  1.4110282e+01, -1.4110001e+02, ...,
          8.5538254e+01,  8.5879929e+01,  2.9760536e+01],
        [ 1.8001239e+02,  1.5024603e+01, -1.5431122e+02, ...,
          8.9706642e+01,  9.6457222e+01,  2.1295717e+01],
        [ 1.6925246e+02,  1.8331032e+01, -1.6412703e+02, ...,
          9.3129837e+01,  1.0565691e+02,  1.3998590e+01],
        ...,
        [ 4.1893402e+01,  4.6106403e+01, -6.6620636e+01, ...,
         -1.0716830e+02,  5.3521276e+00,  1.4658173e+02],
        [ 4.8967632e+01,  3.3375050e+01, -2.3939838e+01, ...,
         -1.1103947e+02,  1.2777783e+01,  1.4931264e+02],
        [ 5.2504749e+01,  2.7009371e+01, -2.5994384e+00, ...,
         -1.1297505e+02,  1.6490612e+01,  1.5067809e+02]],

       [[ 1.7276237e+02,  5.1135506e+01, -9.8375565e+01, ...,
          9.2856529e+01,  1.0043721e+02,  5.6384171e+01],
        [ 1.7325601e+02,  4.1556362e+01, -1.2992981e+02, ...,
          8.7948120e+01,  9.4106003e+01,  5.6865177e+01],
        [ 1.7560381e+02, 